spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/bw_marcenaria}
    username: ${DB_USER:bw_user}
    password: ${DB_PASSWORD:bw_password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    root: INFO
    br.com.bw.backend: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE