spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:mysql://localhost:3307/bw_marcenaria_test}
    username: ${TEST_DB_USER:bw_test}
    password: ${TEST_DB_PASSWORD:bw_test}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    show-sql: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

logging:
  level:
    root: WARN
    br.com.bw.backend: INFO